export const CREATE_POST = "CREATE_POST";
export const UPDATE_POST = "UPDATE_POST";
export const DELETE_POST = "DELETE_POST";
export const FETCH_ALL_POSTS = "FETCH_ALL_POSTS";
export const FETCH_POSTS_BY_LANGUAGE = "FETCH_POSTS_BY_LANGUAGE";
export const FETCH_POSTS_BY_LANGUAGE_AND_MEDIA =
  "FETCH_POSTS_BY_LANGUAGE_AND_MEDIA";
export const FETCH_POSTS_BY_LANGUAGE_AND_CATEGORY =
  "FETCH_POSTS_BY_LANGUAGE_AND_CATEGORY";
export const FETCH_POSTS_BY_LANGUAGE_AND_CATEGORY_AND_MEDIA =
  "FETCH_POSTS_BY_LANGUAGE_AND_CATEGORY_AND_MEDIA";
export const FETCH_POSTS_BY_SEARCH = "FETCH_POSTS_BY_SEARCH";
export const FETCH_POST = "FETCH_POST";
export const FETCH_POST_BY_CREATOR = "FETCH_POST_BY_CREATOR";
export const LIKE_POST = "LIKE_POST";
export const COMMENT_POST = "COMMENT_POST";
export const END_LOADING = "END_LOADING";
export const START_LOADING = "START_LOADING";

export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";

export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";
