import { FETCH_POSTS_BY_LANGUAGE_AND_CATEGORY_AND_MEDIA } from "./actionTypes";

export const posts = [
  {
    title:
      "Best youtube video ever let's just make it a little bit longer to see what happens",
    mediaType: "Video",
    description:
      "whatever a description may look like. Something like this video is so cool bruh you sould watch it let's just make it longer for the sake of testing",
    url: "https://www.google.com",
    creationTime: Date.now(),
    imageUrl: undefined,
    username: "cr1m5onk1ng",
    likesCount: "500",
    easyCount: "120",
    mediumCount: "250",
    advancedCount: "11",
    nativeCount: "0",
  },
  {
    title: "Best youtube video ever",
    mediaType: "Video",
    description:
      "whatever a description may look like. Something like this video is so cool bruh you sould watch it",
    url: "https://www.google.com",
    creationTime: Date.now(),
    imageUrl: undefined,
    username: "cr1m5onk1ng",
    likesCount: "500",
    easyCount: "120",
    mediumCount: "250",
    advancedCount: "11",
    nativeCount: "0",
  },
  {
    title: "Best youtube video ever",
    mediaType: "Video",
    description:
      "whatever a description may look like. Something like this video is so cool bruh you sould watch it",
    url: "https://www.google.com",
    creationTime: Date.now(),
    imageUrl: undefined,
    username: "cr1m5onk1ng",
    likesCount: "500",
    easyCount: "120",
    mediumCount: "250",
    advancedCount: "11",
    nativeCount: "0",
  },
  {
    title: "Best youtube video ever",
    mediaType: "Video",
    description:
      "whatever a description may look like. Something like this video is so cool bruh you sould watch it",
    url: "https://www.google.com",
    creationTime: Date.now(),
    imageUrl: undefined,
    username: "cr1m5onk1ng",
    likesCount: "500",
    easyCount: "120",
    mediumCount: "250",
    advancedCount: "11",
    nativeCount: "0",
  },
  {
    title: "Best youtube video ever",
    mediaType: "Video",
    description:
      "whatever a description may look like. Something like this video is so cool bruh you sould watch it",
    url: "https://www.google.com",
    creationTime: Date.now(),
    imageUrl: undefined,
    username: "cr1m5onk1ng",
    likesCount: "500",
    easyCount: "120",
    mediumCount: "250",
    advancedCount: "11",
    nativeCount: "0",
  },
  {
    title: "Best youtube video ever",
    mediaType: "Video",
    description:
      "whatever a description may look like. Something like this video is so cool bruh you sould watch it",
    url: "https://www.google.com",
    creationTime: Date.now(),
    imageUrl: undefined,
    username: "cr1m5onk1ng",
    likesCount: "500",
    easyCount: "120",
    mediumCount: "250",
    advancedCount: "11",
    nativeCount: "0",
  },
  {
    title: "Best youtube video ever",
    mediaType: "Video",
    description:
      "whatever a description may look like. Something like this video is so cool bruh you sould watch it",
    url: "https://www.google.com",
    creationTime: Date.now(),
    imageUrl: undefined,
    username: "cr1m5onk1ng",
    likesCount: "500",
    easyCount: "120",
    mediumCount: "250",
    advancedCount: "11",
    nativeCount: "0",
  },
  {
    title: "Best youtube video ever",
    mediaType: "Video",
    description:
      "whatever a description may look like. Something like this video is so cool bruh you sould watch it",
    url: "https://www.google.com",
    creationTime: Date.now(),
    imageUrl: undefined,
    username: "cr1m5onk1ng",
    likesCount: "500",
    easyCount: "120",
    mediumCount: "250",
    advancedCount: "11",
    nativeCount: "0",
  },
  {
    title: "Best youtube video ever",
    mediaType: "Video",
    description:
      "whatever a description may look like. Something like this video is so cool bruh you sould watch it",
    url: "https://www.google.com",
    creationTime: Date.now(),
    imageUrl: undefined,
    username: "cr1m5onk1ng",
    likesCount: "500",
    easyCount: "120",
    mediumCount: "250",
    advancedCount: "11",
    nativeCount: "0",
  },
];
