DROP TABLE IF EXISTS comments
DROP TABLE IF EXISTS learning
DROP TABLE IF EXISTS likes
DROP TABLE IF EXISTS resources
DROP TABLE IF EXISTS tags
DROP TABLE IF EXISTS user_post
DROP TABLE IF EXISTS users
DROP TABLE IF EXISTS votes
