// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	AddComment(ctx context.Context, arg AddCommentParams) (DiscussionComment, error)
	AddPost(ctx context.Context, arg AddPostParams) (UserPost, error)
	AddPostDiscussion(ctx context.Context, arg AddPostDiscussionParams) (PostDiscussion, error)
	AddResource(ctx context.Context, arg AddResourceParams) (Resource, error)
	AddResourceToStudyList(ctx context.Context, arg AddResourceToStudyListParams) (StudyListResource, error)
	AddStudyList(ctx context.Context, arg AddStudyListParams) (StudyList, error)
	AddToken(ctx context.Context, arg AddTokenParams) (Token, error)
	AddUserTargetLanguage(ctx context.Context, arg AddUserTargetLanguageParams) (Learning, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAllDiscussionComments(ctx context.Context, arg GetAllDiscussionCommentsParams) ([]DiscussionComment, error)
	GetAllDiscussionCommentsByCursor(ctx context.Context, arg GetAllDiscussionCommentsByCursorParams) ([]DiscussionComment, error)
	GetAllUserComments(ctx context.Context, arg GetAllUserCommentsParams) ([]DiscussionComment, error)
	GetAllUserPostComments(ctx context.Context, arg GetAllUserPostCommentsParams) ([]DiscussionComment, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetCommentDirectResponses(ctx context.Context, arg GetCommentDirectResponsesParams) ([]DiscussionComment, error)
	GetCommentLikes(ctx context.Context, commentID int64) ([]CommentsLike, error)
	GetCommentLikesCount(ctx context.Context, commentID int64) (int64, error)
	GetCommunitiesPosts(ctx context.Context, arg GetCommunitiesPostsParams) ([]GetCommunitiesPostsRow, error)
	GetCommunitiesPostsByCursor(ctx context.Context, arg GetCommunitiesPostsByCursorParams) ([]GetCommunitiesPostsByCursorRow, error)
	GetDiscussionCommentById(ctx context.Context, id int64) (DiscussionComment, error)
	GetPostById(ctx context.Context, id string) (UserPost, error)
	GetPostDifficultyVotes(ctx context.Context, postID string) ([]Vote, error)
	GetPostDiscussionById(ctx context.Context, id int64) (PostDiscussion, error)
	GetPostDiscussions(ctx context.Context, arg GetPostDiscussionsParams) ([]PostDiscussion, error)
	GetPostDiscussionsByCursor(ctx context.Context, arg GetPostDiscussionsByCursorParams) ([]PostDiscussion, error)
	GetPostDiscussionsByUser(ctx context.Context, arg GetPostDiscussionsByUserParams) ([]PostDiscussion, error)
	GetPostDiscussionsByUserByCursor(ctx context.Context, arg GetPostDiscussionsByUserByCursorParams) ([]PostDiscussion, error)
	GetPostLikes(ctx context.Context, postID string) ([]Like, error)
	GetPostTags(ctx context.Context, postID string) ([]Tag, error)
	GetPosts(ctx context.Context, arg GetPostsParams) ([]GetPostsRow, error)
	GetPostsByCategory(ctx context.Context, arg GetPostsByCategoryParams) ([]UserPost, error)
	GetPostsByCursor(ctx context.Context, arg GetPostsByCursorParams) ([]GetPostsByCursorRow, error)
	GetPostsByDifficulty(ctx context.Context, arg GetPostsByDifficultyParams) ([]UserPost, error)
	GetPostsByLanguage(ctx context.Context, arg GetPostsByLanguageParams) ([]UserPost, error)
	GetPostsByMediaType(ctx context.Context, arg GetPostsByMediaTypeParams) ([]UserPost, error)
	GetPostsByTopic(ctx context.Context, arg GetPostsByTopicParams) ([]UserPost, error)
	GetPostsByUser(ctx context.Context, arg GetPostsByUserParams) ([]UserPost, error)
	GetResourceById(ctx context.Context, id int64) (Resource, error)
	GetResourceByUrl(ctx context.Context, url string) (Resource, error)
	GetResourcePost(ctx context.Context, resourceID int64) (UserPost, error)
	GetResourcesByLanguage(ctx context.Context, arg GetResourcesByLanguageParams) ([]Resource, error)
	GetResourcesByLanguageByCursor(ctx context.Context, arg GetResourcesByLanguageByCursorParams) ([]Resource, error)
	GetResourcesPostsByUser(ctx context.Context, arg GetResourcesPostsByUserParams) ([]Resource, error)
	GetStudyList(ctx context.Context, id int64) (StudyList, error)
	GetStudyListResources(ctx context.Context, studyListID int64) ([]Resource, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserFollowers(ctx context.Context, id string) ([]GetUserFollowersRow, error)
	GetUserSavedResources(ctx context.Context, userID string) ([]GetUserSavedResourcesRow, error)
	GetUserStudyLists(ctx context.Context, userID string) ([]StudyList, error)
	GetUserTargetLanguages(ctx context.Context, userID string) ([]Learning, error)
	GetVote(ctx context.Context, arg GetVoteParams) (Vote, error)
	GetVotes(ctx context.Context, postID string) ([]Vote, error)
	InvalidateToken(ctx context.Context, token string) error
	LikeComment(ctx context.Context, arg LikeCommentParams) error
	RemoveAllUserStudyLists(ctx context.Context, userID string) error
	RemoveComment(ctx context.Context, id int64) error
	RemoveDiscussionComments(ctx context.Context, discussionID int64) error
	RemovePost(ctx context.Context, id string) error
	RemovePostDiscussion(ctx context.Context, id int64) error
	RemovePostDiscussionsByCreator(ctx context.Context, creatorID string) error
	RemoveResourceFromStudyList(ctx context.Context, resourceID int64) error
	RemoveStudyList(ctx context.Context, id int64) error
	RemoveUser(ctx context.Context, id string) error
	RemoveUserComments(ctx context.Context, userID string) error
	RemoveUserPosts(ctx context.Context, userID string) error
	RemoveVote(ctx context.Context, arg RemoveVoteParams) error
	UnlikeComment(ctx context.Context, arg UnlikeCommentParams) error
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (DiscussionComment, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (UserPost, error)
	UpdatePostDiscussion(ctx context.Context, arg UpdatePostDiscussionParams) (PostDiscussion, error)
	UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error)
	UpdateStudyList(ctx context.Context, arg UpdateStudyListParams) (StudyList, error)
	UpdateUserLanguage(ctx context.Context, arg UpdateUserLanguageParams) (User, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	UpdateUserToken(ctx context.Context, arg UpdateUserTokenParams) (User, error)
	UpdateVote(ctx context.Context, arg UpdateVoteParams) (Vote, error)
	VotePost(ctx context.Context, arg VotePostParams) (Vote, error)
}

var _ Querier = (*Queries)(nil)
